### ISSUE TITLE
Links to definition in source fail to load

### ISSUE THREAD

**Issue by AndrewADev** [JamesLMilner/terra-draw-website#1]
Currently, clicking on a link on a link to the location of a definition:
![image](https://github.com/JamesLMilner/terra-draw-website/assets/2937540/9210fe83-139b-4402-bb53-94f852d3d88a)

...leads to a non-working page:
![image](https://github.com/JamesLMilner/terra-draw-website/assets/2937540/fa2d2086-7a9d-40e0-bb53-8d5daee04c42)

...because [GitHub's CSP prevents use of iframes](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html#preventing-framing-attacks-clickjacking-cross-site-leaks)
![image](https://github.com/JamesLMilner/terra-draw-website/assets/2937540/fff7feae-6b88-4713-a65d-40cf42294870)

...one of which is used in the [main API docs component](https://github.com/JamesLMilner/terra-draw-website/blob/e47ec69611c89deab4793cf5862b03fde485285a/src/routes/api-docs/index.tsx#L6).

## Possible fix: 

For the markup itself, the change is as simple as not trying to display GitHub content within an `<iframe>`, instead using something else, likely a  `<div>` (screenshot from the TypeDoc example site): 
![image](https://github.com/JamesLMilner/terra-draw-website/assets/2937540/a28f0d14-badc-4a9e-bd28-7ecf35f7d468)

But as this iframe is currently [pointing to an html file hosted on GitHub pages](https://github.com/JamesLMilner/terra-draw-website/blob/e47ec69611c89deab4793cf5862b03fde485285a/src/routes/api-docs/index.tsx#L9), there would certainly be more changes needed as well.

**Comment by JamesLMilner** [comment]
Thanks for raising this @AndrewADev, appreciated. This is an issue I hadn't noticed - I think the best option is to disable it for now via the `disablesSources` flag, although this feels like a shame. Another option would be to post process the output to make all the links of this type open in a new tab, although that would be quite laborious.

I've raised an issue on TypeDoc to ask if it's possible to add a flag to enable opening these links in another tab that you can see here: https://github.com/TypeStrong/typedoc/issues/2415

**Comment by JamesLMilner** [comment]
@AndrewADev this should be resolved now just to the addition of the upstream flag to open links in a new tab 👍🏻
