### ISSUE TITLE
Ommisions from API docs

### ISSUE THREAD

**Issue by morehawes** [JamesLMilner/terra-draw-website#2]
Hi @JamesLMilner,

I noticed that the following classes are not currently included in the API docs:

- [TerraDrawArcGISMapsSDKAdapter](https://jameslmilner.github.io/terra-draw/classes/TerraDrawArcGISMapsSDKAdapter.html)
- [TerraDrawStaticMode](https://jameslmilner.github.io/terra-draw/classes/TerraDrawStaticMode.html)

When I get time I will try looking into this one myself.

**Comment by morehawes** [comment]
More API docs omissions. Included in the Guides [Common Patterns](https://github.com/morehawes/terra-draw/blob/main/guides/COMMON_PATTERNS.md) section, but not found in the docs:

- draw.getFeaturesAtPointerEvent()
- draw.getFeaturesAtLngLat()

**Comment by JamesLMilner** [comment]
I would have to double check, but would imagine we just need to run the docs script again to rebuild the docs site for these to appear. Will look at doing that when I get a moment!
